version: '3'
services:
    db:
        image: mariadb:10.4
        command: --default-authentication-plugin=mysql_native_password
        environment:
            #MYSQL_RANDOM_ROOT_PASSWORD: "yes"
            MYSQL_ROOT_PASSWORD: "rootpassword"
            MYSQL_USER: smfuser
            MYSQL_PASSWORD: smfpass 
            MYSQL_DATABASE: smfdb
        volumes:
          - mysql_data:/var/lib/mysql
          - ./db/in:/docker-entrypoint-initdb.d:ro
    web:
        build: web
        ports:
            - "8000:80"
        depends_on:
            - db
        volumes:
          - ./web/data:/var/www/html
    pma:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8001:80"
        depends_on:
            - db
        environment:
            PMA_HOST: "db"
            PMA_ARBITRARY: 1
volumes:
    mysql_data:
    #smf_data:
